server:
  port: 8080

jwt:
  secret: "12345678901234567890123456789012"

spring:
  main:
    web-application-type: reactive
  application:
    name: auto-api-gateway-service

  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                  - "http://10.0.2.2:8081"
                  - "http://localhost:8081"
                  - "http://192.168.1.144:8081"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                allowedHeaders: "*"
                exposedHeaders:
                  - Authorization
                allowCredentials: true
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auto-auth-service-route
              uri: lb://auto-auth-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: auto-auth-service-circuitbreaker
                    fallbackUri: /fallback/auto-auth-service-fallback
            - id: auto-car-service-route
              uri: lb://auto-car-service
              predicates:
                - Path=/car/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: auto-car-service-circuitbreaker
                    fallbackUri: /fallback/auto-car-service-fallback
            - id: auto-document-service-route
              uri: lb://auto-document-service
              predicates:
                - Path=/document/**
              filters:
                - StripPrefix=1
                - name: CircuitBreaker
                  args:
                    name: auto-document-service-circuitbreaker
                    fallbackUri: /fallback/auto-document-service-fallback

resilience4j:
  circuitbreaker:
    instances:
      auto-auth-service-circuitbreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
      auto-car-service-circuitbreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
      auto-document-service-circuitbreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
  timelimiter:
    instances:
      auto-auth-service-circuitbreaker:
        timeoutDuration: 3s
      auto-car-service-circuitbreaker:
        timeoutDuration: 3s
      auto-document-service-circuitbreaker:
        timeoutDuration: 3s

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
  health:
    consul:
      enabled: true

# Logging
logging:
  level:
    root: INFO
    auto.trace: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"